package com.u1.model;

import java.util.Date;
import java.util.List;

// Generated 2013-11-1 15:29:18 by Hibernate Tools 3.4.0.CR1

/**
 * AssetAttributes generated by hbm2java
 */
public class AssetAttribute implements java.io.Serializable {

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "AssetAttribute [assetAttrbutePid=" + assetAttrbutePid
			 + ", attributeTemplatePid="
				+ attributeTemplatePid + ", stringValue=" + stringValue
				+ ", booleanValue=" + booleanValue + ", floatValue="
				+ floatValue + ", doubleValue=" + doubleValue
				+ ", integerValue=" + integerValue + ", dateValue=" + dateValue
				+ ", selectedOptionList=" + selectedOptionList + "]";
	}
	public AssetAttribute(){
	}
	
	private Integer assetAttrbutePid;
//	private Integer assetPid;
	private Asset asset;
	private Integer attributeTemplatePid;
	private String stringValue;
	private Boolean booleanValue;
	private Float floatValue;
	private Double doubleValue;
	private Integer integerValue;
	private Date dateValue;
	private List<AttrSelectOption> selectedOptionList;
	/**
	 * @return the assetAttrbutePid
	 */
	public Integer getAssetAttrbutePid() {
		return assetAttrbutePid;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((assetAttrbutePid == null) ? 0 : assetAttrbutePid.hashCode());
		return result;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AssetAttribute other = (AssetAttribute) obj;
		if (assetAttrbutePid == null) {
			if (other.assetAttrbutePid != null)
				return false;
		} else if (!assetAttrbutePid.equals(other.assetAttrbutePid))
			return false;
		return true;
	}
	/**
	 * @param assetAttrbutePid the assetAttrbutePid to set
	 */
	public void setAssetAttrbutePid(Integer assetAttrbutePid) {
		this.assetAttrbutePid = assetAttrbutePid;
	}
	
	/**
	 * @return the asset
	 */
	public Asset getAsset() {
		return asset;
	}
	/**
	 * @param asset the asset to set
	 */
	public void setAsset(Asset asset) {
		this.asset = asset;
	}
	/**
	 * @return the attributeTemplatePid
	 */
	public Integer getAttributeTemplatePid() {
		return attributeTemplatePid;
	}
	/**
	 * @param attributeTemplatePid the attributeTemplatePid to set
	 */
	public void setAttributeTemplatePid(Integer attributeTemplatePid) {
		this.attributeTemplatePid = attributeTemplatePid;
	}
	/**
	 * @return the stringValue
	 */
	public String getStringValue() {
		return stringValue;
	}
	/**
	 * @param stringValue the stringValue to set
	 */
	public void setStringValue(String stringValue) {
		this.stringValue = stringValue;
	}
	/**
	 * @return the booleanValue
	 */
	public Boolean getBooleanValue() {
		return booleanValue;
	}
	/**
	 * @param booleanValue the booleanValue to set
	 */
	public void setBooleanValue(Boolean booleanValue) {
		this.booleanValue = booleanValue;
	}
	/**
	 * @return the floatValue
	 */
	public Float getFloatValue() {
		return floatValue;
	}
	/**
	 * @param floatValue the floatValue to set
	 */
	public void setFloatValue(Float floatValue) {
		this.floatValue = floatValue;
	}
	/**
	 * @return the doubleValue
	 */
	public Double getDoubleValue() {
		return doubleValue;
	}
	/**
	 * @param doubleValue the doubleValue to set
	 */
	public void setDoubleValue(Double doubleValue) {
		this.doubleValue = doubleValue;
	}
	/**
	 * @return the integerValue
	 */
	public Integer getIntegerValue() {
		return integerValue;
	}
	/**
	 * @param integerValue the integerValue to set
	 */
	public void setIntegerValue(Integer integerValue) {
		this.integerValue = integerValue;
	}
	/**
	 * @return the dateValue
	 */
	public Date getDateValue() {
		return dateValue;
	}
	/**
	 * @param dateValue the dateValue to set
	 */
	public void setDateValue(Date dateValue) {
		this.dateValue = dateValue;
	}
	/**
	 * @return the selectedOptionList
	 */
	public List<AttrSelectOption> getSelectedOptionList() {
		return selectedOptionList;
	}
	/**
	 * @param selectedOptionList the selectedOptionList to set
	 */
	public void setSelectedOptionList(List<AttrSelectOption> selectedOptionList) {
		this.selectedOptionList = selectedOptionList;
	}
	
	
}
