package com.u1.model;

// Generated 2013-12-19 21:15:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.validation.constraints.Pattern;
import javax.validation.groups.Default;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * TaskLog generated by hbm2java
 */
public class AssetLog extends Log {
	private Integer assetPid;
//	@Pattern(regexp = "^n$|^c$|^u$|^f$", message="{Pattern.tasklog.actioncode}")
	private String actionCode;
	
	public AssetLog(){
		super();
	}
	
	public AssetLog(Integer assetPid, String actionCode, RefUser owner, String remark,String autoremark) {
		super(owner,remark,autoremark);
		this.assetPid = assetPid;
		this.actionCode = actionCode;
	}

	/**
	 * @return the assetPid
	 */
	public Integer getAssetPid() {
		return assetPid;
	}

	/**
	 * @param assetPid the assetPid to set
	 */
	public void setAssetPid(Integer assetPid) {
		this.assetPid = assetPid;
	}

	/**
	 * @return the actionCode
	 */
	public String getActionCode() {
		return actionCode;
	}

	/**
	 * @param actionCode the actionCode to set
	 */
	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}
	
}
