package com.u1.model;

// Generated 2013-12-29 0:32:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Attachment generated by hbm2java
 */
public class Attachment implements java.io.Serializable {

	private Integer atmId;
	private Integer taskId;
	private Integer assetId;
	private String filename;
	private String storefilename;
	private Date lastupdatetimestamp;
	private Boolean enabled;
	private String remark;
	private String type;
	private Long size;
	private SimpleUsers owner;

	public Attachment() {
	}

	public Attachment(Integer taskId, Integer assetId, String filename,
			String storefilename, Date lastupdatetimestamp, Boolean enabled,
			String remark, String type, Long size, SimpleUsers owner) {
		this.taskId = taskId;
		this.assetId = assetId;
		this.filename = filename;
		this.storefilename = storefilename;
		this.lastupdatetimestamp = lastupdatetimestamp;
		this.enabled = enabled;
		this.remark = remark;
		this.type = type;
		this.size = size;
		this.owner=owner;
	}
	
	public Attachment(Integer taskId, Integer assetId, String filename, String storefilename,String remark, String type, Long size, SimpleUsers owner){
		this.taskId = taskId;
		this.assetId = assetId;
		this.filename = filename;
		this.storefilename = storefilename;
		this.enabled = true;
		this.remark = remark;
		this.type = type;
		this.size = size;
		this.owner = owner;
	}

	/**
	 * @return the owner
	 */
	public SimpleUsers getOwner() {
		return owner;
	}

	/**
	 * @param owner the owner to set
	 */
	public void setOwner(SimpleUsers owner) {
		this.owner = owner;
	}

	public Integer getAtmId() {
		return this.atmId;
	}

	public void setAtmId(Integer atmId) {
		this.atmId = atmId;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public Integer getAssetId() {
		return this.assetId;
	}

	public void setAssetId(Integer assetId) {
		this.assetId = assetId;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getStorefilename() {
		return this.storefilename;
	}

	public void setStorefilename(String storefilename) {
		this.storefilename = storefilename;
	}

	public Date getLastupdatetimestamp() {
		return this.lastupdatetimestamp;
	}

	public void setLastupdatetimestamp(Date lastupdatetimestamp) {
		this.lastupdatetimestamp = lastupdatetimestamp;
	}

	/**
	 * @return the size
	 */
	public Long getSize() {
		return size;
	}

	/**
	 * @param size the size to set
	 */
	public void setSize(Long size) {
		this.size = size;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
