package com.u1.model;

// Generated 2014-3-5 12:24:15 by Hibernate Tools 3.4.0.CR1

/**
 * Componentstore generated by hbm2java
 */
public class Componentstore implements java.io.Serializable {

	private Integer componentStoreId;
//	private int componentId;
	private Component component;
	private Integer customerId;
//	private Customer customer;
	private Integer count;
	private Boolean enabled;

	public Componentstore() {
	}
	
	public Componentstore(Integer componentStoreId){
		this.componentStoreId=componentStoreId;
	}

//	public Componentstore(int componentId, int customerId, int count,
//			int enabled) {
//		this.componentId = componentId;
//		this.customerId = customerId;
//		this.count = count;
//		this.enabled = enabled;
//	}

	public Integer getComponentStoreId() {
		return this.componentStoreId;
	}

	public void setComponentStoreId(Integer componentStoreId) {
		this.componentStoreId = componentStoreId;
	}

//	public int getComponentId() {
//		return this.componentId;
//	}
//
//	public void setComponentId(int componentId) {
//		this.componentId = componentId;
//	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	/**
	 * @return the component
	 */
	public Component getComponent() {
		return component;
	}

	/**
	 * @param component the component to set
	 */
	public void setComponent(Component component) {
		this.component = component;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Componentstore [componentStoreId=" + componentStoreId
				+ ", component=" + component + ", customerId=" + customerId
				+ ", count=" + count + ", enabled=" + enabled + "]";
	}

//	/**
//	 * @return the customer
//	 */
//	public Customer getCustomer() {
//		return customer;
//	}
//
//	/**
//	 * @param customer the customer to set
//	 */
//	public void setCustomer(Customer customer) {
//		this.customer = customer;
//	}

}
