package com.u1.model;

// Generated 2014-3-11 17:31:30 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.validation.constraints.Digits;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.groups.Default;

import com.u1.model.SimpleAsset0.Entity;
import com.u1.model.TaskForUpdate.Done;

/**
 * Componentrecord generated by hbm2java
 */
public class Componentrecord implements java.io.Serializable {

	private Integer componentrecordId;
//	private Integer componentstoreId;
	private Componentstore componentstore;
//	private Integer customerId;
//	private Integer userId;
//	private Integer taskId;
	@Min(value = 1, message = "{Digits.Componentrecord.quantity}")
	@Max(value = 99999, message = "{Digits.Componentrecord.quantity}")
	@NotNull(message="{Digits.Componentrecord.quantity}")
	private Integer quantity;
	@Digits(integer = 10, fraction = 2, message = "{Digits.Componentrecord.price}")
	@NotNull(groups=NeedPrice.class, message="{Digits.Componentrecord.price}")
	private Double price;
	@Min(value = 1, message = "{Digits.Componentrecord.reason}")
	@Max(value = 7, message = "{Digits.Componentrecord.reason}")
	@NotNull(message="{Digits.Componentrecord.reason}")
	private Integer reason;
	@Pattern(regexp=ModelConstants.REG_CHN_ALLOW_EMPTY_100, message="{Pattern.Componentrecord.remark}")
	private String remark;
	private Date createdDatetime;
	private RefUser user;
//	private RefTask task;
	private TaskLog taskLog;
	private Integer logQuantity;

	/**
	 * @return the user
	 */
	public RefUser getUser() {
		return user;
	}


	/**
	 * @param user the user to set
	 */
	public void setUser(RefUser user) {
		this.user = user;
	}


//	/**
//	 * @return the task
//	 */
//	public RefTask getTask() {
//		return task;
//	}
//
//
//	/**
//	 * @param task the task to set
//	 */
//	public void setTask(RefTask task) {
//		this.task = task;
//	}


	public Componentrecord() {
	}


//	public Componentrecord(Integer componentrecordId){
//		this.componentrecordId=componentrecordId;
//	}


	/**
	 * @return the taskLog
	 */
	public TaskLog getTaskLog() {
		return taskLog;
	}


	/**
	 * @return the componentstore
	 */
	public Componentstore getComponentstore() {
		return componentstore;
	}


	/**
	 * @param componentstore the componentstore to set
	 */
	public void setComponentstore(Componentstore componentstore) {
		this.componentstore = componentstore;
	}


	/**
	 * @param taskLog the taskLog to set
	 */
	public void setTaskLog(TaskLog taskLog) {
		this.taskLog = taskLog;
	}


	public Integer getComponentrecordId() {
		return this.componentrecordId;
	}

	public void setComponentrecordId(Integer componentrecordId) {
		this.componentrecordId = componentrecordId;
	}

//	public Integer getComponentstoreId() {
//		return this.componentstoreId;
//	}
//
//	public void setComponentstoreId(Integer componentstoreId) {
//		this.componentstoreId = componentstoreId;
//	}

//	public Integer getCustomerId() {
//		return this.customerId;
//	}
//
//	public void setCustomerId(Integer customerId) {
//		this.customerId = customerId;
//	}

//	public Integer getUserId() {
//		return this.userId;
//	}
//
//	public void setUserId(Integer userId) {
//		this.userId = userId;
//	}



	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getReason() {
		return this.reason;
	}

	public void setReason(Integer reason) {
		this.reason = reason;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}



//	/**
//	 * @return the taskId
//	 */
//	public Integer getTaskId() {
//		return taskId;
//	}
//
//	/**
//	 * @param taskId the taskId to set
//	 */
//	public void setTaskId(Integer taskId) {
//		this.taskId = taskId;
//	}

	/**
	 * @return the createdDatetime
	 */
	public Date getCreatedDatetime() {
		return createdDatetime;
	}

	/**
	 * @param createdDatetime the createdDatetime to set
	 */
	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	/**
	 * @param reason the reason to set
	 */
	public void setReason(int reason) {
		this.reason = reason;
	}


	/**
	 * @return the logQuantity
	 */
	public Integer getLogQuantity() {
		return logQuantity;
	}


	/**
	 * @param logQuantity the logQuantity to set
	 */
	public void setLogQuantity(Integer logQuantity) {
		this.logQuantity = logQuantity;
	}


	public interface NeedPrice extends Default{}


	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((componentrecordId == null) ? 0 : componentrecordId
						.hashCode());
		return result;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Componentrecord other = (Componentrecord) obj;
		if (componentrecordId == null) {
			if (other.componentrecordId != null)
				return false;
		} else if (!componentrecordId.equals(other.componentrecordId))
			return false;
		return true;
	}




}
