package com.u1.model;

// Generated 2014-1-20 17:35:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.validation.constraints.Pattern;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {
	private Integer customerId;
	@Pattern(regexp=ModelConstants.REG_CHN_20, message="{Pattern.customer.customerName}")
	private String customerName;
	@Pattern(regexp=ModelConstants.REG_CHN_ALLOW_EMPTY_100, message="{Pattern.customer.customerDesc}")
	private String customerDesc;
	private Boolean enabled;
	private Integer createdBy;
	private Date createdTimestamp;
	private Integer lastUpdatedBy;
	private Date lastUpdatedTimestamp;

	public Customer() {
	}
	
	public Customer(Integer id) {
		this.customerId=id;
	}
	
//	public Customer(String id){
//		this.customerId=Integer.valueOf(id);
//	}

	public Customer(String customerName, String customerDesc, Boolean enabled,
			Integer createdBy, Date createdTimestamp, Integer lastUpdatedBy,
			Date lastUpdatedTimestamp) {
		this.customerName = customerName;
		this.customerDesc = customerDesc;
		this.enabled = enabled;
		this.createdBy = createdBy;
		this.createdTimestamp = createdTimestamp;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedTimestamp = lastUpdatedTimestamp;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCustomerDesc() {
		return this.customerDesc;
	}

	public void setCustomerDesc(String customerDesc) {
		this.customerDesc = customerDesc;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getLastUpdatedTimestamp() {
		return this.lastUpdatedTimestamp;
	}

	public void setLastUpdatedTimestamp(Date lastUpdatedTimestamp) {
		this.lastUpdatedTimestamp = lastUpdatedTimestamp;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Customer [customerId=" + customerId + ", customerName="
				+ customerName + ", customerDesc=" + customerDesc
				+ ", enabled=" + enabled + ", createdBy=" + createdBy
				+ ", createdTimestamp=" + createdTimestamp + ", lastUpdatedBy="
				+ lastUpdatedBy + ", lastUpdatedTimestamp="
				+ lastUpdatedTimestamp + "]";
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((customerId == null) ? 0 : customerId.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Customer other = (Customer) obj;
		if (customerId == null) {
			if (other.customerId != null)
				return false;
		} else if (!customerId.equals(other.customerId))
			return false;
		return true;
	}



}
