package com.u1.model;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

// Generated 2013-9-21 23:13:02 by Hibernate Tools 3.4.0.CR1

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer departmentPid;
	@Pattern(regexp=ModelConstants.REG_CHN_20, message="{Pattern.department.departmentName}")
	private String departmentName;
	@Pattern(regexp=ModelConstants.REG_CHN_ALLOW_EMPTY_100, message="{Pattern.department.departmentDesc}")
	private String departmentDesc;
	private Boolean enabled;
	@NotNull(message="{NotNull.customer}")
	private Customer customer;

	public Department() {
	}
	
	public Department(String strid){
		this.departmentPid=Integer.valueOf(strid);
	}

	public Integer getDepartmentPid() {
		return this.departmentPid;
	}

	public void setDepartmentPid(Integer departmentPid) {
		this.departmentPid = departmentPid;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getDepartmentDesc() {
		return this.departmentDesc;
	}

	public void setDepartmentDesc(String departmentDesc) {
		this.departmentDesc = departmentDesc;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	/**
	 * @return the customer
	 */
	public Customer getCustomer() {
		return customer;
	}

	/**
	 * @param customer the customer to set
	 */
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Department [departmentPid=" + departmentPid
				+ ", departmentName=" + departmentName + ", departmentDesc="
				+ departmentDesc + ", enabled=" + enabled + ", customer="
				+ customer + "]";
	}


}
