package com.u1.model;

import java.util.List;

// Generated 2013-9-1 21:26:47 by Hibernate Tools 3.4.0.CR1

/**
 * Groups generated by hbm2java
 */
public class GroupWithRole extends Groups0{
	private List<Roles> roleList;

	public GroupWithRole(){
		super();
	}
	
	/**
	 * @return the roleList
	 */
	public List<Roles> getRoleList() {
		return roleList;
	}

	/**
	 * @param roleList the roleList to set
	 */
	public void setRoleList(List<Roles> roleList) {
		this.roleList = roleList;
	}
	
}