package com.u1.model;

import java.util.List;

import javax.validation.constraints.Pattern;

// Generated 2013-9-1 21:26:47 by Hibernate Tools 3.4.0.CR1

/**
 * Groups generated by hbm2java
 */
public class Groups0 implements java.io.Serializable {

	private Integer groupId;
	
	@Pattern(regexp=ModelConstants.REG_CHN_20, message="{Pattern.groups.groupName}")
	private String groupName;
//	private List<Users> userList;



//	/**
//	 * @return the userList
//	 */
//	public List<Users> getUserList() {
//		return userList;
//	}
//
//	/**
//	 * @param userList the userList to set
//	 */
//	public void setUserList(List<Users> userList) {
//		this.userList = userList;
//	}

	public Groups0() {
	}

	public Groups0(String groupName) {
		this.groupName = groupName;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

}
