package com.u1.model;

import java.util.List;

import javax.validation.constraints.Pattern;

// Generated 2013-9-1 21:26:47 by Hibernate Tools 3.4.0.CR1

/**
 * Groups generated by hbm2java
 */
public class Groups extends Groups0{
	
	public Groups(){
		super();
	}
	
	public Groups(String groupIdStr){
		this.setGroupId(Integer.valueOf(groupIdStr));
	}
	
	//overwrite groupname to allow empty input for search
	@Pattern(regexp=ModelConstants.REG_CHN_ALLOW_EMPTY_20, message="{Pattern.groups.groupName}")
	private String groupName;
	
	private List<SimpleUsers> userList;
	
	
	/**
	 * @return the userList
	 */
	public List<SimpleUsers> getUserList() {
		return userList;
	}

	/**
	 * @param userList the userList to set
	 */
	public void setUserList(List<SimpleUsers> userList) {
		this.userList = userList;
	}

	/**
	 * @return the groupName
	 */
	public String getGroupName() {
		return groupName;
	}

	/**
	 * @param groupName the groupName to set
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}
}