package com.u1.model;

import java.util.List;

import javax.validation.constraints.Pattern;

// Generated 2013-9-3 7:16:25 by Hibernate Tools 3.4.0.CR1

/**
 * Roles generated by hbm2java
 */
public class Roles extends Roles0{
	
	//overwrite rolename to allow empty input for search
	@Pattern(regexp=ModelConstants.REG_CHN_ALLOW_EMPTY_20, message="{Pattern.roles.roleName}")
	private String roleName;
	
	/**
	 * @return the roleName
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * @param roleName the roleName to set
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Roles(){
		super();
	}
	
	public Roles(String roleIdStr){
		super.setRoleId(Integer.valueOf(roleIdStr));
	}
	
	private List<Groups> groupList;

	/**
	 * @return the groupList
	 */
	public List<Groups> getGroupList() {
		return groupList;
	}

	/**
	 * @param groupList the groupList to set
	 */
	public void setGroupList(List<Groups> groupList) {
		this.groupList = groupList;
	}
	
}