package com.u1.model;

// Generated 2013-8-14 16:29:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.Length;

/**
 * Users generated by hbm2java
 */
public class SimpleUsers0 implements java.io.Serializable {

	private Integer userId;
	@Pattern(regexp=ModelConstants.REG_CHN_20, message="{Pattern.users.username}")
	private String username;
//	private String password;
//	private String userType;
//	private boolean accountNonExpired;
//	private boolean accountNonLocked;
//	private boolean credentialsNonExpired;
	private Boolean enabled;
	private Date createdTimestamp;
	private Date lastUpdatedTimestamp;
//	private String salt;
//	private String companyName;
	@Pattern(regexp=ModelConstants.REG_CHN_20, message="{Pattern.users.givenName}")
	private String givenName;
//	private String familyName;
//	private String gender;
//	private Integer age;
//	private Date birthday;
	@Pattern(regexp=ModelConstants.EMAIL,message="{Pattern.users.email}")
	@Length(max=50, message="{Pattern.users.email}")
	private String email;
	@Pattern(regexp=ModelConstants.TEL, message="{Pattern.users.telephone}")
	private String telephone;
//	private String address1;
//	private String address2;
//	private String address3;
//	private String phone1;
//	private String phone2;
//	private String phone3;
//	private String photo;
//	private String degree;
//	private String englishName;
//	private String position;
//	private String graduateSchool;
//	private String major;
//	private String fax;
//	private String qq;
//	private String website;
//	private String msn;
	@NotNull(message="{NotNull.users.customer}")
	private Customer customer;


	public SimpleUsers0() {
	}
	
	public SimpleUsers0(Integer id){
		this.userId = id;
	}

	public SimpleUsers0(String idstr){
		this.userId=Integer.valueOf(idstr);
	}

//	public Users(String username, String password, boolean accountNonExpired,
//			boolean accountNonLocked, boolean credentialsNonExpired,
//			boolean enabled, Date createdTimestamp, Date lastUpdatedTimestamp,
//			String salt) {
//		this.username = username;
//		this.password = password;
//		this.accountNonExpired = accountNonExpired;
//		this.accountNonLocked = accountNonLocked;
//		this.credentialsNonExpired = credentialsNonExpired;
//		this.enabled = enabled;
//		this.createdTimestamp = createdTimestamp;
//		this.lastUpdatedTimestamp = lastUpdatedTimestamp;
//		this.salt = salt;
//	}

//	public Users(String username, String password, String userType,
//			boolean accountNonExpired, boolean accountNonLocked,
//			boolean credentialsNonExpired, boolean enabled,
//			Date createdTimestamp, Date lastUpdatedTimestamp, String salt,
//			String companyName, String givenName, String familyName,
//			String gender, Integer age, Date birthday, String email,
//			String telephone, String address1, String address2,
//			String address3, String phone1, String phone2, String phone3,
//			String photo, String degree, String englishName, String position,
//			String graduateSchool, String major, String fax, String qq,
//			String website, String msn) {
//		this.username = username;
//		this.password = password;
//		this.userType = userType;
//		this.accountNonExpired = accountNonExpired;
//		this.accountNonLocked = accountNonLocked;
//		this.credentialsNonExpired = credentialsNonExpired;
//		this.enabled = enabled;
//		this.createdTimestamp = createdTimestamp;
//		this.lastUpdatedTimestamp = lastUpdatedTimestamp;
//		this.salt = salt;
//		this.companyName = companyName;
//		this.givenName = givenName;
//		this.familyName = familyName;
//		this.gender = gender;
//		this.age = age;
//		this.birthday = birthday;
//		this.email = email;
//		this.telephone = telephone;
//		this.address1 = address1;
//		this.address2 = address2;
//		this.address3 = address3;
//		this.phone1 = phone1;
//		this.phone2 = phone2;
//		this.phone3 = phone3;
//		this.photo = photo;
//		this.degree = degree;
//		this.englishName = englishName;
//		this.position = position;
//		this.graduateSchool = graduateSchool;
//		this.major = major;
//		this.fax = fax;
//		this.qq = qq;
//		this.website = website;
//		this.msn = msn;
//	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

//	public String getPassword() {
//		return this.password;
//	}
//
//	public void setPassword(String password) {
//		this.password = password;
//	}

//	public String getUserType() {
//		return this.userType;
//	}
//
//	public void setUserType(String userType) {
//		this.userType = userType;
//	}
//
//	public boolean isAccountNonExpired() {
//		return this.accountNonExpired;
//	}
//
//	public void setAccountNonExpired(boolean accountNonExpired) {
//		this.accountNonExpired = accountNonExpired;
//	}
//
//	public boolean isAccountNonLocked() {
//		return this.accountNonLocked;
//	}
//
//	public void setAccountNonLocked(boolean accountNonLocked) {
//		this.accountNonLocked = accountNonLocked;
//	}
//
//	public boolean isCredentialsNonExpired() {
//		return this.credentialsNonExpired;
//	}
//
//	public void setCredentialsNonExpired(boolean credentialsNonExpired) {
//		this.credentialsNonExpired = credentialsNonExpired;
//	}

	public Boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Date getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	public Date getLastUpdatedTimestamp() {
		return this.lastUpdatedTimestamp;
	}

	public void setLastUpdatedTimestamp(Date lastUpdatedTimestamp) {
		this.lastUpdatedTimestamp = lastUpdatedTimestamp;
	}

//	public String getSalt() {
//		return this.salt;
//	}
//
//	public void setSalt(String salt) {
//		this.salt = salt;
//	}
//
//	public String getCompanyName() {
//		return this.companyName;
//	}
//
//	public void setCompanyName(String companyName) {
//		this.companyName = companyName;
//	}

	public String getGivenName() {
		return this.givenName;
	}

	public void setGivenName(String givenName) {
		this.givenName = givenName;
	}

//	public String getFamilyName() {
//		return this.familyName;
//	}
//
//	public void setFamilyName(String familyName) {
//		this.familyName = familyName;
//	}
//
//	public String getGender() {
//		return this.gender;
//	}
//
//	public void setGender(String gender) {
//		this.gender = gender;
//	}
//
//	public Integer getAge() {
//		return this.age;
//	}
//
//	public void setAge(Integer age) {
//		this.age = age;
//	}
//
//	public Date getBirthday() {
//		return this.birthday;
//	}
//
//	public void setBirthday(Date birthday) {
//		this.birthday = birthday;
//	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}



	/**
	 * @return the customer
	 */
	public Customer getCustomer() {
		return customer;
	}

	/**
	 * @param customer the customer to set
	 */
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "SimpleUsers0 [userId=" + userId + ", username=" + username
				+ ", enabled=" + enabled
				+ ", createdTimestamp=" + createdTimestamp
				+ ", lastUpdatedTimestamp=" + lastUpdatedTimestamp
				+ ", givenName=" + givenName + ", email=" + email
				+ ", telephone=" + telephone + "]";
	}

//	public String getAddress1() {
//		return this.address1;
//	}
//
//	public void setAddress1(String address1) {
//		this.address1 = address1;
//	}
//
//	public String getAddress2() {
//		return this.address2;
//	}
//
//	public void setAddress2(String address2) {
//		this.address2 = address2;
//	}
//
//	public String getAddress3() {
//		return this.address3;
//	}
//
//	public void setAddress3(String address3) {
//		this.address3 = address3;
//	}
//
//	public String getPhone1() {
//		return this.phone1;
//	}
//
//	public void setPhone1(String phone1) {
//		this.phone1 = phone1;
//	}
//
//	public String getPhone2() {
//		return this.phone2;
//	}
//
//	public void setPhone2(String phone2) {
//		this.phone2 = phone2;
//	}
//
//	public String getPhone3() {
//		return this.phone3;
//	}
//
//	public void setPhone3(String phone3) {
//		this.phone3 = phone3;
//	}
//
//	public String getPhoto() {
//		return this.photo;
//	}
//
//	public void setPhoto(String photo) {
//		this.photo = photo;
//	}
//
//	public String getDegree() {
//		return this.degree;
//	}
//
//	public void setDegree(String degree) {
//		this.degree = degree;
//	}
//
//	public String getEnglishName() {
//		return this.englishName;
//	}
//
//	public void setEnglishName(String englishName) {
//		this.englishName = englishName;
//	}
//
//	public String getPosition() {
//		return this.position;
//	}
//
//	public void setPosition(String position) {
//		this.position = position;
//	}
//
//	public String getGraduateSchool() {
//		return this.graduateSchool;
//	}
//
//	public void setGraduateSchool(String graduateSchool) {
//		this.graduateSchool = graduateSchool;
//	}
//
//	public String getMajor() {
//		return this.major;
//	}
//
//	public void setMajor(String major) {
//		this.major = major;
//	}
//
//	public String getFax() {
//		return this.fax;
//	}
//
//	public void setFax(String fax) {
//		this.fax = fax;
//	}
//
//	public String getQq() {
//		return this.qq;
//	}
//
//	public void setQq(String qq) {
//		this.qq = qq;
//	}
//
//	public String getWebsite() {
//		return this.website;
//	}
//
//	public void setWebsite(String website) {
//		this.website = website;
//	}
//
//	public String getMsn() {
//		return this.msn;
//	}
//
//	public void setMsn(String msn) {
//		this.msn = msn;
//	}

}
