package com.u1.model;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.groups.Default;

import com.u1.model.TaskForUpdate.Done;
import com.u1.model.TaskForUpdate.ReValue;

// Generated 2013-12-31 1:43:15 by Hibernate Tools 3.4.0.CR1

/**
 * Slaconfig generated by hbm2java
 */
public class Slaconfig implements java.io.Serializable {
	private Integer idslaconfig;
	@Min(value = 1, message = "{slaconfig.seloption}")
    @Max(value = 2, message = "{slaconfig.seloption}")
	@NotNull(message="{slaconfig.seloption}")
	private Integer seloption;
	@Min(groups=Option1.class, value = 1, message = "{slaconfig.option1inteval}")
    @Max(groups=Option1.class, value = 100, message = "{slaconfig.option1inteval}")
	@NotNull(groups=Option1.class, message="{slaconfig.option1inteval}")
	private Integer option1inteval;
	@Min(groups=Option1.class, value = 1, message = "{slaconfig.option1deduction}")
    @Max(groups=Option1.class, value = 100, message = "{slaconfig.option1deduction}")
	@NotNull(groups=Option1.class, message="{slaconfig.option1deduction}")
	private Integer option1deduction;
	@Min(groups=Option2.class, value = 1, message = "{slaconfig.option2inteval}")
    @Max(groups=Option2.class, value = 100, message = "{slaconfig.option2inteval}")
	@NotNull(groups=Option2.class, message="{slaconfig.option2inteval}")
	private Integer option2inteval;
	@Min(groups=Option2.class, value = 1, message = "{slaconfig.option2deduction}")
    @Max(groups=Option2.class, value = 100, message = "{slaconfig.option2deduction}")
	@NotNull(groups=Option2.class, message="{slaconfig.option2deduction}")
	private Integer option2deduction;

	public Slaconfig() {
	}

	public Slaconfig(Integer seloption, Integer option1inteval,
			Integer option1deduction, Integer option2inteval,
			Integer option2deduction) {
		this.seloption = seloption;
		this.option1inteval = option1inteval;
		this.option1deduction = option1deduction;
		this.option2inteval = option2inteval;
		this.option2deduction = option2deduction;
	}

	public Integer getIdslaconfig() {
		return this.idslaconfig;
	}

	public void setIdslaconfig(Integer idslaconfig) {
		this.idslaconfig = idslaconfig;
	}

	public Integer getSeloption() {
		return this.seloption;
	}

	public void setSeloption(Integer seloption) {
		this.seloption = seloption;
	}

	public Integer getOption1inteval() {
		return this.option1inteval;
	}

	public void setOption1inteval(Integer option1inteval) {
		this.option1inteval = option1inteval;
	}

	public Integer getOption1deduction() {
		return this.option1deduction;
	}

	public void setOption1deduction(Integer option1deduction) {
		this.option1deduction = option1deduction;
	}

	public Integer getOption2inteval() {
		return this.option2inteval;
	}

	public void setOption2inteval(Integer option2inteval) {
		this.option2inteval = option2inteval;
	}

	public Integer getOption2deduction() {
		return this.option2deduction;
	}

	public void setOption2deduction(Integer option2deduction) {
		this.option2deduction = option2deduction;
	}
	public interface Option1 extends Default{};
	public interface Option2 extends Default{};
}
