package com.u1.model;

import javax.validation.constraints.Digits;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.Pattern;


// Generated 2013-9-24 17:26:52 by Hibernate Tools 3.4.0.CR1

/**
 * TaskType generated by hbm2java
 */
public class TaskType implements java.io.Serializable {
    private Integer taskTypePid;
    @Pattern(regexp = ModelConstants.REG_CHN_20, message = "{Pattern.tasktype.code}")
    private String code;
    @Pattern(regexp = ModelConstants.REG_CHN_ALLOW_EMPTY_20, message = "{Pattern.tasktype.description}")
    private String description;
    private Boolean enabled;
    @Min(value = 0, message = "{tasktype.highDefaultTime}")
    @Max(value = 9999, message = "{tasktype.highDefaultTime}")
    private Integer highDefaultTime;
    @Min(value = 0, message = "{tasktype.mediumDefaultTime}")
    @Max(value = 9999, message = "{tasktype.mediumDefaultTime}")
    private Integer mediumDefaultTime;
    @Min(value = 0, message = "{tasktype.lowDefaultTime}")
    @Max(value = 9999, message = "{tasktype.lowDefaultTime}")
    private Integer lowDefaultTime;
    private String iconName;
    @Min(value = 0, message = "{tasktype.weight}")
    @Max(value = 9999, message = "{tasktype.weight}")
    private Integer weight;
    @Pattern(regexp = ModelConstants.DEFINED_CODE, message = "{DEFINED_CODE}")
    private String definedCode;
//    private Integer definedNum;

    public TaskType() {
    }

    public TaskType(String idstr) {
        this.taskTypePid = Integer.valueOf(idstr);
    }

    /**
     * @return the taskTypePid
     */
    public Integer getTaskTypePid() {
        return taskTypePid;
    }

    /**
     * @param taskTypePid the taskTypePid to set
     */
    public void setTaskTypePid(Integer taskTypePid) {
        this.taskTypePid = taskTypePid;
    }

    /**
     * @return the code
     */
    public String getCode() {
        return code;
    }

    /**
     * @param code the code to set
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the enabled
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * @param enabled the enabled to set
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * @return the highDefaultTime
     */
    public Integer getHighDefaultTime() {
        return highDefaultTime;
    }

    /**
     * @param highDefaultTime the highDefaultTime to set
     */
    public void setHighDefaultTime(Integer highDefaultTime) {
        this.highDefaultTime = highDefaultTime;
    }

    /**
     * @return the mediumDefaultTime
     */
    public Integer getMediumDefaultTime() {
        return mediumDefaultTime;
    }

    /**
     * @param mediumDefaultTime the mediumDefaultTime to set
     */
    public void setMediumDefaultTime(Integer mediumDefaultTime) {
        this.mediumDefaultTime = mediumDefaultTime;
    }

    /**
     * @return the lowDefaultTime
     */
    public Integer getLowDefaultTime() {
        return lowDefaultTime;
    }

    /**
     * @param lowDefaultTime the lowDefaultTime to set
     */
    public void setLowDefaultTime(Integer lowDefaultTime) {
        this.lowDefaultTime = lowDefaultTime;
    }

    /**
     * @return the iconName
     */
    public String getIconName() {
        return iconName;
    }

    /**
     * @param iconName the iconName to set
     */
    public void setIconName(String iconName) {
        this.iconName = iconName;
    }

    /**
     * @return the weight
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * @param weight the weight to set
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * @return the definedCode
     */
    public String getDefinedCode() {
        return definedCode;
    }

    /**
     * @param definedCode the definedCode to set
     */
    public void setDefinedCode(String definedCode) {
        this.definedCode = definedCode;
    }

//    /**
//     * @return the definedNum
//     */
//    public Integer getDefinedNum() {
//        return definedNum;
//    }
//
//    /**
//     * @param definedNum the definedNum to set
//     */
//    public void setDefinedNum(Integer definedNum) {
//        this.definedNum = definedNum;
//    }

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "TaskType [taskTypePid=" + taskTypePid + ", code=" + code +
        ", description=" + description + ", enabled=" + enabled +
        ", highDefaultTime=" + highDefaultTime + ", mediumDefaultTime=" +
        mediumDefaultTime + ", lowDefaultTime=" + lowDefaultTime +
        ", iconName=" + iconName + ", weight=" + weight + ", definedCode=" +
        definedCode + "]";
    }
}
