package com.u1.model;

// Generated 2013-12-19 21:15:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.groups.Default;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * TaskLog generated by hbm2java
 */
public class TaskLog extends Log {
//	private Integer taskPid;
	private RefTask task;
	@Pattern(regexp = "^n$|^c$|^r$|^p$|^a$|^i$|^d$|^v$|^f$|^s$", message="{Pattern.tasklog.actioncode}")   //s for component select
	@NotNull(message="{Pattern.tasklog.actioncode}")
	private String actionCode;
	private RefUser assignedTo;
	private List<Componentrecord> recordList;

	
	public TaskLog(){
		super();
	}
	
	public TaskLog(RefTask task, String actionCode, RefUser assignedTo, RefUser owner, String remark,String autoremark) {
		super(owner,remark,autoremark);
		this.task = task;
		this.actionCode = actionCode;
		this.assignedTo = assignedTo;
	}
	
	/**
	 * @return the taskPid
	 */
	public RefTask getTask() {
		return task;
	}
	/**
	 * @param taskPid the taskPid to set
	 */
	public void setTask(RefTask task) {
		this.task = task;
	}
	/**
	 * @return the actionCode
	 */
	public String getActionCode() {
		return actionCode;
	}
	/**
	 * @param actionCode the actionCode to set
	 */
	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}
	/**
	 * @return the assignedTo
	 */
	public RefUser getAssignedTo() {
		return assignedTo;
	}
	/**
	 * @param assignedTo the assignedTo to set
	 */
	public void setAssignedTo(RefUser assignedTo) {
		this.assignedTo = assignedTo;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "TaskLog [task=" + task + ", actionCode=" + actionCode
				+ ", assignedTo=" + assignedTo + ","+super.toString()+"]";
	}

	/**
	 * @return the recordList
	 */
	public List<Componentrecord> getRecordList() {
		return recordList;
	}

	/**
	 * @param recordList the recordList to set
	 */
	public void setRecordList(List<Componentrecord> recordList) {
		this.recordList = recordList;
	}
	
	
}
